# Generated by Django 2.0.4 on 2018-04-17 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapi', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Data',
            new_name='emp',
        ),
    ]
