# Generated by Django 2.0.4 on 2018-04-17 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapi', '0002_auto_20180417_1542'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emp',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
